### PR TITLE
Don't validate pure objects

### LINKED ISSUE #220: Primitive query parameters that are not required fail validation
When a query parameter is not required, the type is OneOf primtive type and null. 

When validating the url the query value won't get coerced properly because of this and this causes invalid type errors.

@amarzavery   Should we just not make the query parameters nullable ? Don't think it makes sense to have them as nullable.

### PR DESCRIPTION
**Pull request by vladbarosan**
Fixes #220

### CODE REVIEW

**Comment by mcardosos** [comment]
Cool! Something to add are tests.
There are already some tests for queries here:
https://github.com/Azure/oav/blob/master/test/modelValidation/swaggers/specification/query/test.json
But they don't take if params are required or not yet :)

**Comment by vladbarosan** [comment]
@mcardosos those are for example validations where the issue wont come up since in the example its already parsed.

**Comment by vladbarosan** [comment]
Apparently at least the live validator tests were never running because the path given was wrong and no swaggers were being loaded.

Also we should actually validate the expected errors as right now we just wait for exceptions. I opened the issue here #222

**Comment by vladbarosan** [comment]
Changed title as the fix for the optional query parameters was made in Sway https://github.com/amarzavery/sway/pull/24

**Pull request merged**
